language: python
python:
  - "3.6"
services:
  - docker
install:
  - pip install virtualenv --upgrade
  - make install
  - make test-install
script:
  - make test
deploy:
  provider: script
  script: chmod +x deploy.sh && deploy.sh
  skip_cleanup: true
  on:
    tags: true
    python: "3.6"
